"""ICAO / FAA NOTAM contractions -> plain English.

A deliberately *curated* map: we only expand codes we are confident about, so
that station identifiers and names (e.g. VOR "MRM", locator "COL") are left
untouched. This is the deterministic layer — the LLM never has to guess these.

Extend freely as new codes show up in real NOTAMs. Keys are matched only as
whole tokens (see clean.expand_abbreviations), so order does not matter.
"""

CONTRACTIONS: dict[str, str] = {
    # --- runway / taxiway / apron ---
    "RWY": "runway",
    "TWY": "taxiway",
    "APN": "apron",
    "PRKG": "parking",
    "TWYS": "taxiways",
    "RWYS": "runways",
    "TDZ": "touchdown zone",
    "THR": "threshold",
    "STWL": "stopway lights",
    "TORA": "takeoff run available",
    "TODA": "takeoff distance available",
    "ASDA": "accelerate-stop distance available",
    "LDA": "landing distance available",
    # --- status / condition ---
    "CLSD": "closed",
    "U/S": "unserviceable",
    "UNSERVICEABLE": "unserviceable",
    "OPR": "operating",
    "OPS": "operations",
    "MAINT": "maintenance",
    "TEMPO": "temporary",
    "PERM": "permanent",
    "SUSPENDED": "suspended",
    "AVBL": "available",
    "UNAVBL": "unavailable",
    "WEF": "with effect from",
    "TIL": "until",
    "EXC": "except",
    "DLY": "daily",
    "BTN": "between",
    "REF": "reference",
    "ADZ": "advise",
    "CTC": "contact",
    "POSS": "possible",
    "DUE": "due",
    "WI": "within",
    # --- navaids ---
    "ILS": "instrument landing system",
    "LOC": "localizer",
    "GP": "glidepath",
    "DME": "distance measuring equipment",
    "VOR": "VHF omnidirectional range",
    "DVOR": "doppler VOR",
    "VORTAC": "VOR/TACAN",
    "DVORTAC": "doppler VOR/TACAN",
    "NDB": "non-directional beacon",
    "TACAN": "tactical air navigation",
    "MM": "middle marker",
    "OM": "outer marker",
    "IM": "inner marker",
    "GBAS": "ground-based augmentation system",
    "SBAS": "satellite-based augmentation system",
    # --- procedures ---
    "APCH": "approach",
    "APP": "approach",
    "DEP": "departure",
    "ARR": "arrival",
    "SID": "standard instrument departure",
    "STAR": "standard arrival route",
    "PROC": "procedure",
    "PROCS": "procedures",
    "FNA": "final approach",
    "IAP": "instrument approach procedure",
    "RNAV": "area navigation",
    "RNP": "required navigation performance",
    "LPV": "localizer performance with vertical guidance",
    "LNAV": "lateral navigation",
    "VNAV": "vertical navigation",
    "OCA": "obstacle clearance altitude",
    "OCH": "obstacle clearance height",
    "MDA": "minimum descent altitude",
    "MNM": "minimum",
    "MAX": "maximum",
    "MINIMA": "minima",
    # --- obstacles / lighting ---
    "OBST": "obstacle",
    "OBSTS": "obstacles",
    "TWR": "tower",
    "CRANE": "crane",
    "LGT": "light",
    "LGTS": "lights",
    "LGTD": "lighted",
    "UNLGTD": "unlighted",
    "PAPI": "precision approach path indicator",
    "ABN": "aerodrome beacon",
    # --- airspace / units ---
    "AD": "aerodrome",
    "FIR": "flight information region",
    "CTR": "control zone",
    "TMA": "terminal control area",
    "ATZ": "aerodrome traffic zone",
    "FIS": "flight information service",
    "AFIS": "aerodrome flight information service",
    "ATC": "air traffic control",
    "TWR/AD": "tower",
    "MIL": "military",
    "CIV": "civil",
    "QRA": "quick reaction alert",
    "ALTN": "alternate",
    # --- aircraft / ops ---
    "ACFT": "aircraft",
    "HEL": "helicopter",
    "FLT": "flight",
    "FREQ": "frequency",
    "INFO": "information",
    "SVC": "service",
    "COORD": "coordinate",
    "PSN": "position",
    "INS": "inertial navigation system",
    # --- units / measures ---
    "FT": "feet",
    "AMSL": "above mean sea level",
    "AGL": "above ground level",
    "NM": "nautical miles",
    "KM": "kilometres",
    "MHZ": "MHz",
    "KHZ": "kHz",
    "RDL": "radial",
    "MAG": "magnetic",
    "TRUE": "true",
    # --- time ---
    "UTC": "UTC",
    "SR": "sunrise",
    "SS": "sunset",
    "HR": "hour",
    "HRS": "hours",
    "MIN": "minutes",
}
