"""How many people use the app, and how much — anonymously.

Two numbers, and only two: how many briefings have been built, and how many
distinct devices built them. The device identity is a random string the browser
makes up for itself once and keeps in localStorage (see web/index.html). It is
not derived from anything — not the IP, not the phone, not the pilot — so it
answers "how many users" without being able to answer "which users".

Same lifetime as usage.py: in-memory and per-process, so it resets on every
redeploy. The keep-alive workflow polls it and folds the result into the same
secret Gist that holds the token totals (.github/scripts/log_usage.py) — the
device roster is *unioned* there rather than summed, so a returning pilot is
counted once no matter how many redeploys happen in between.

Wiring — record() called by server.py on each /briefing; snapshot() read by
server.py for /stats and /stats.json. Calls nothing internal.
"""

from __future__ import annotations

import re
import threading

_lock = threading.Lock()
_briefings = 0
_devices: set[str] = set()

# A device ID is generated by us (16 hex chars), but it arrives from the network,
# so treat it as untrusted: anything that isn't the shape we issue is dropped
# rather than stored. The cap stops a malicious client from growing the set
# without bound — at real usage (tens of pilots) it is never approached.
_ID_RE = re.compile(r"\A[a-z0-9]{8,64}\Z")
_MAX_DEVICES = 10_000


def record(device_id: str) -> None:
    """Count one briefing, and the device that asked for it (if it sent an ID)."""
    global _briefings
    with _lock:
        _briefings += 1
        did = str(device_id or "").strip().lower()
        if _ID_RE.match(did) and len(_devices) < _MAX_DEVICES:
            _devices.add(did)


def snapshot(with_devices: bool = False) -> dict:
    """Counts since this server last started.

    `with_devices` includes the raw roster — only for the key-protected endpoint
    the keep-alive job reads, because that is what makes the union across
    redeploys possible. Never expose it publicly.
    """
    with _lock:
        out = {"briefings": _briefings, "devices": len(_devices)}
        if with_devices:
            out["device_ids"] = sorted(_devices)
        return out


def reset() -> None:
    global _briefings
    with _lock:
        _briefings = 0
        _devices.clear()
